version: '3.8'

services:
  node-server:
    container_name: node-server
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - my-network

  react-app:
    container_name: react-app
    build:
      context: ./client
    ports:
      - '80:80'
    env_file:
      - ./client/.env
    depends_on:
      - node-server
    restart: on-failure
    networks:
      - my-network

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    env_file:
      - .env.mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongo-data:/data/db
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge
